<a href="https://colab.research.google.com/github/KostantinDubnitskyi/Methodd/blob/main/%D0%9B%D0%B5%D0%BA%D1%86%D1%96%D1%8F1(%D0%94%D1%83%D0%B1%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9_4_8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук до лекції 2  
## NumPy: масиви, векторизація та лінійна алгебра для машинного навчання

Ноутбук повторює та закріплює приклади, розглянуті в лекції.  
Усі основні приклади можна виконувати послідовно зверху вниз.

**Мета:** навчитися працювати з `ndarray`, індексацією, `dtype`, векторизацією, broadcasting, агрегуванням, зміною форми масивів, генерацією випадкових даних і засобами `numpy.linalg`.


In [17]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


### Самостійно
Створіть матрицю розміру `(3, 4)` та перевірте її `shape`, `ndim`, `size`, `dtype` і `nbytes`.


In [18]:
# Ваш код

m2 = np.arange(12).reshape(3, 4)

print("shape:", m2.shape)
print("ndim:", m2.ndim)
print("size:", m2.size)
print("dtype:", m2.dtype)
print("nbytes:", m2.nbytes)

shape: (3, 4)
ndim: 2
size: 12
dtype: int64
nbytes: 96


### Самостійно
Створіть масив типу `float64` і перетворіть його на `float32`. Порівняйте `itemsize` і `nbytes`.


In [19]:
# Ваш код
x = np.array([1, 2, 3], dtype=np.float64)
y = x.astype(np.float32)

print("x.dtype:", x.dtype)
print("y.dtype:", y.dtype)

print("x.itemsize:", x.itemsize)
print("y.itemsize:", y.itemsize)

print("x.nbytes:", x.nbytes)
print("y.nbytes:", y.nbytes)

x.dtype: float64
y.dtype: float32
x.itemsize: 8
y.itemsize: 4
x.nbytes: 24
y.nbytes: 12


In [21]:
# Ваш код
scores = np.array([56, 82, 91, 47, 73])

mask = (scores >= 70) & (scores <= 90)

print("mask:", mask)
print("scores[mask]:", scores[mask])

mask: [False  True False False  True]
scores[mask]: [82 73]


### Самостійно
До кожного стовпця матриці додайте різне число за допомогою broadcasting.


In [23]:
# Ваш код
x = np.array([
    [170., 65.],
    [180., 80.],
    [160., 55.]
])

numb = np.array([1, -5])

print("X.shape:", x.shape)
print("numb.shape:", numb.shape)

print("\nX + numb =\n", x + numb)

X.shape: (3, 2)
numb.shape: (2,)

X + numb =
 [[171.  60.]
 [181.  75.]
 [161.  50.]]


### Самостійно
Згенеруйте:
- матрицю `(4, 3)` із нормального розподілу;
- 10 випадкових цілих чисел від 1 до 100;
- випадкову вибірку з 5 різних індексів із діапазону `0..19`.


In [24]:
# Ваш код
rng = np.random.default_rng(seed=42)
normal_matrix = rng.normal(loc=0.0, scale=1.0, size=(4, 3))
random_ints = rng.integers(1, 101, size=10)

print("normal_matrix:", normal_matrix)
print("random_ints:", random_ints)

rng = np.random.default_rng(123)

random_sample = rng.choice(np.arange(20), size=5, replace=False)

print("\nrandom_sample:", random_sample)

normal_matrix: [[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]]
random_ints: [79 65 41 83 55 45 46 23 10 56]

random_sample: [ 1 10  0 18 11]


## 19. Підсумкові тренувальні завдання

1. Створіть матрицю `X` форми `(5, 4)` із випадкових чисел.
2. Обчисліть середнє та стандартне відхилення кожної ознаки.
3. Стандартизуйте матрицю через broadcasting.
4. Виберіть рядки, у яких значення першої ознаки додатне.
5. Додайте до матриці новий стовпець одиниць.
6. Створіть вектор ваг і обчисліть прогноз `X @ w`.
7. Для заданого `y_true` обчисліть MSE.
8. Перевірте, чи немає в масивах `NaN` або `inf`.


In [25]:
# 1. Матриця X форми (5, 4) із випадкових чисел
rng = np.random.default_rng(seed=7)
X = rng.normal(loc=50, scale=10, size=(5, 4))

# 2. Середнє та стандартне відхилення кожної ознаки
P = X.mean(axis=0)
S = X.std(axis=0)

print("P:", P)
print("S:", S)

# 3. Стандартизація через broadcasting
X_std = (X - P) / S

print("X_std =", X_std)

# 4. Рядки, у яких значення першої ознаки додатне
mask = X[:, 0] > 0
X_positive = X[mask]

print("Рядки з додатною першою ознакою:", X_positive)

# 5. Додаємо стовпець одиниць
X_d = np.column_stack([
    np.ones(X_std.shape[0]),
    X_std
])

print("X_d =", X_d)

# 6. Вектор ваг і прогноз
w = np.array([1.0, 0.5, -0.3, 0.8, 0.2])
y_pred = X_d @ w

print("y_pred =", y_pred)

# 7. MSE для заданого y_true
y_true = np.array([48., 52., 47., 55., 50.])
mse = np.mean((y_true - y_pred) ** 2)

print("MSE =", mse)

# 8. Перевірка на NaN та inf
print("Є NaN:", np.isnan(X).any())
print("Є inf:", np.isinf(X).any())

P: [45.6311051  44.59708055 46.69074647 50.42455174]
S: [5.12378195 4.63294059 8.23001784 9.85295993]
X_std = [[ 0.85507082  1.81102577  0.06900046 -0.94697129]
 [-0.03470346 -0.97422922  0.47517389  1.31712712]
 [-0.10796132 -0.17307141  0.99728508  0.31912424]
 [ 1.05840519 -0.84217808  0.36655271  0.66259076]
 [-1.77081122  0.17845293 -1.90801213 -1.35187083]]
Рядки з додатною першою ознакою: [[50.01230153 52.98745538 47.25862145 41.09408161]
 [45.45329215 40.08353445 50.60143603 63.40215246]
 [45.07793481 43.795251   54.8984205  53.56887008]
 [51.05414249 40.69531955 49.70748178 56.95303194]
 [36.55785453 45.42384239 30.9877726  37.1046226 ]]
X_d = [[ 1.          0.85507082  1.81102577  0.06900046 -0.94697129]
 [ 1.         -0.03470346 -0.97422922  0.47517389  1.31712712]
 [ 1.         -0.10796132 -0.17307141  0.99728508  0.31912424]
 [ 1.          1.05840519 -0.84217808  0.36655271  0.66259076]
 [ 1.         -1.77081122  0.17845293 -1.90801213 -1.35187083]]
y_pred = [ 0.75003378  