<a href="https://colab.research.google.com/github/KostantinDubnitskyi/Methodd/blob/main/%D0%9B%D1%801(%D0%94%D1%83%D0%B1%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі

In [4]:
import numpy as np
np.__version__

'2.0.2'

In [43]:
#1 Задати Вектор
v=np.array([1, 2, 3, 4, 5], dtype=float)
v

array([1., 2., 3., 4., 5.])

In [44]:
v[0]

np.float64(1.0)

In [45]:
v[-1]

np.float64(5.0)

In [83]:
#2 Задати Матрицю 3*2
a=np.array([[4, 2, 5],
            [0, 1, 9]])
a

array([[4, 2, 5],
       [0, 1, 9]])

In [84]:
#3 Вивести елемент a22
a[1, 1]

np.int64(1)

In [85]:
#4 Вивести елемент a11
a[0, 0]

np.int64(4)

In [86]:
#5 Вивести тип елементів
a.dtype

dtype('int64')

In [87]:
a.size

6

In [88]:
a.shape

(2, 3)

In [89]:
#6 Задаемо Матрицю 3*3
a=np.array([[20, 4, 1], [7, 2, 16], [11, 8, 15]])
a

array([[20,  4,  1],
       [ 7,  2, 16],
       [11,  8, 15]])

In [90]:
#7 Ще один варіант задати матрицю
b= np.matrix([[14, 5, 7], [17, 21, 1], [3, 0, 9]])
b

matrix([[14,  5,  7],
        [17, 21,  1],
        [ 3,  0,  9]])

In [91]:
#8 Побудуемо діагональ
diag_a=np.diag(a)
diag_a

array([20,  2, 15])

In [92]:
#9 Побудуемо діагональну матрицю на основі діагоналі
a_diag=np.diag(diag_a)
a_diag

array([[20,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, 15]])

In [93]:
#10 Масив вектор, заповнений нулями
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [94]:
#11 Створіть двовимірний масив розміром 3*3, заповніть його нулями та виведіть його значення.
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [95]:
#12 Створіть масив розміром 4*4, заповніть його випадковими числами в діапазоні від 0 до 10 та виведіть його значення.
np.random.randint(11, size=(4,4))

array([[1, 8, 9, 2],
       [2, 1, 3, 2],
       [2, 5, 2, 4],
       [0, 9, 1, 8]])

In [96]:
#13 Масив (вектор) заповнений одиницями
np.ones(5)

array([1., 1., 1., 1., 1.])

In [97]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [98]:
#14 Масив чисел від 2 до 9 з кроком 2
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [99]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [65]:
#15 Матриця з одиниць розміром 3*3
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [100]:
#16 Транспонувати матрицю
a=np.array([[20, 4, 1], [7, 2, 16], [11, 8, 15]])
a

array([[20,  4,  1],
       [ 7,  2, 16],
       [11,  8, 15]])

In [101]:
a.transpose()

array([[20,  7, 11],
       [ 4,  2,  8],
       [ 1, 16, 15]])

In [102]:
a.T

array([[20,  7, 11],
       [ 4,  2,  8],
       [ 1, 16, 15]])

In [103]:
#17 Визначник матриці
a=np.array([[6, 5], [3, 1]])
a


array([[6, 5],
       [3, 1]])

In [104]:
a_det= np.linalg.det(a)
a_det

np.float64(-8.999999999999998)

In [105]:
#18 Множення матриці на число
a=np.matrix([[11, 4, 31], [9, -2, 6]])
c=3*a
c

matrix([[33, 12, 93],
        [27, -6, 18]])

In [106]:
#19 Додавання матриць
a=np.matrix([[11, 4, 31], [9, -2, 6]])
b= np.matrix([[8, 1, 5], [6, 9, 12]])
c=b+a
c

matrix([[19,  5, 36],
        [15,  7, 18]])

In [107]:
#20 Добуток матриць
a= np.matrix([[9, 2], [4, 1]])
b= np.matrix([[6, 9], [7, 5]])
c=np.dot(a,b)
c

matrix([[68, 91],
        [31, 41]])

In [108]:
#поелементний добуток
np.multiply(a, b)

matrix([[54, 18],
        [28,  5]])

In [109]:
a/b

matrix([[1.5       , 0.22222222],
        [0.57142857, 0.2       ]])

In [110]:
np.divide(a, b)

matrix([[1.5       , 0.22222222],
        [0.57142857, 0.2       ]])

In [113]:
#21 Обернена матриця
a= np.matrix([[4, -8], [1, 7]])

a_inv=np.linalg.inv(a)
a_inv

matrix([[ 0.19444444,  0.22222222],
        [-0.02777778,  0.11111111]])

In [114]:
#22 Ранг матриці
rank=np.linalg.matrix_rank(a)
rank

np.int64(2)

In [115]:
a=np.array([[11, 4, 31], [9, -2, 6]])
b=np.array([[8, 1, 5], [6, 9, 12]])
c1=a*b
print("Поелементний добуток матриць:")
print(c1)

Поелементний добуток матриць:
[[ 88   4 155]
 [ 54 -18  72]]


In [117]:
a=np.array([[1, -6, -10],
       [2, 9, 5],
       [0, -4, 12]])
eigenvalues, eigenvectors= np.linalg.eig(a)

In [118]:
print("Власні числа:")
print(eigenvalues)

Власні числа:
[3.88298563+0.j         9.05850718+2.93178122j 9.05850718-2.93178122j]


In [119]:
print("\nВласні вектори:")
print(eigenvectors)


Власні вектори:
[[-0.95936688+0.j          0.77313105+0.j          0.77313105-0.j        ]
 [ 0.25309856+0.j         -0.45243328+0.06313859j -0.45243328-0.06313859j]
 [ 0.12472495+0.j         -0.35156825-0.26454827j -0.35156825+0.26454827j]]
