<a href="https://colab.research.google.com/github/KostantinDubnitskyi/Methodd/blob/main/%D0%9B%D1%801(%D0%94%D1%83%D0%B1%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9_4_8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

In [ ]:
import numpy as np

## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [ ]:
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
print("a + b =", a+b)
print("a - b =", a-b)
print("4 * a =", 4*a)
print("-2 * b =",-2*b)
print("a * b =", a*b)

a + b = [10  4  4 13]
a - b = [ 4 -8  6  5]
4 * a = [28 -8 20 36]
-2 * b = [ -6 -12   2  -8]
a * b = [ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.

In [ ]:
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])

#1 Обчисліть скалярний добуток двома способами: np.dot() і оператором @.
dot_np = np.dot(u, v)
dot_sop = u @ v
print("dot_np =", dot_np)
print("dot_sop =", dot_sop)

#2 Знайдіть евклідову норму кожного вектора.
norma_u = np.linalg.norm(u)
norma_v = np.linalg.norm(v)
print("norma_u =", norma_u)
print("norma_v =", norma_v)

#3 Обчисліть косинус кута між вектора
cos_angle = dot_np / (norma_u * norma_v)
print("cos(angle) =", cos_angle)

dot_np = 31
dot_sop = 31
norma_u = 7.0
norma_v = 6.48074069840786
cos(angle) = 0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [ ]:
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])
B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
#1
print("A + B =", A + B)

#2
print("A - B =", A - B)

#3
print("A * B  =", A * B)

#4
print("5 * A =", 5 * A)

#5
print("A^T =", A.T)

A + B = [[4 3 5]
 [9 3 6]]
A - B = [[ 2  7 -7]
 [-5 -3  2]]
A * B  = [[  3 -10  -6]
 [ 14   0   8]]
5 * A = [[15 25 -5]
 [10  0 20]]
A^T = [[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [ ]:
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])
B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

#1 Обчисліть матричний добуток A @ B.
C = A @ B
print("A @ B =", C)

#2 Визначте форму результату.
print("Форма результата:", C.shape)

#3 Обчисліть елемент результату з індексами [0, 1] вручну через відповідний рядок A і стовпець B та перевірте його.
row0 = A[0, :]
col1 = B[:, 1]
map = np.dot(row0, col1)
print("Рядок 0 матриці A:", row0)
print("Стовбчик 1 матриці B:", col1)
print("Ручний розрахунок C[0,1] =", map)
print("Из відповіді, C[0,1] =", C[0, 1])
print("Співпадають:", map == C[0, 1])

A @ B = [[17  7]
 [32  5]]
Форма результата: (2, 2)
Рядок 0 матриці A: [2 1 3]
Стовбчик 1 матриці B: [2 0 1]
Ручний розрахунок C[0,1] = 7
Из відповіді, C[0,1] = 7
Співпадають: True


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [ ]:
v = np.array([12, 7, 19, 4, 11, 8])

#1 Виконайте циклічний зсув на 2 позиції вправо.
move_right = np.roll(v, 2)
print("Зсув на 2 вправо:", move_right)

#2 Виконайте циклічний зсув на 3 позиції вліво.
move_left = np.roll(v, -3)
print("Зсув на 3 вліво: ", move_left)

#3 Відновіть початковий вектор із результату першого зсуву.
restored = np.roll(move_left, 3)
print("Відновлений вектор:", restored)
print("Чи повернений до оригіналу:", np.array_equal(restored, v))

Зсув на 2 вправо: [11  8 12  7 19  4]
Зсув на 3 вліво:  [ 4 11  8 12  7 19]
Відновлений вектор: [12  7 19  4 11  8]
Чи повернений до оригіналу: True


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [ ]:
v = np.array([42, 17, 29, 8, 35, 23])

#1 Відсортуйте елементи за зростанням.
up_sort = np.sort(v)
print("За зростанням:", up_sort)

#2 Відсортуйте елементи за спаданням.
down_sort = np.sort(v)[::-1]
print("За спаданням: ", down_sort)

#3 Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.
indecs_down = np.argsort(v)[::-1]
print("Індекси (спадання):", indecs_down)
print("Перевірка v:", v[indecs_down])

За зростанням: [ 8 17 23 29 35 42]
За спаданням:  [42 35 29 23 17  8]
Індекси (спадання): [0 4 2 5 1 3]
Перевірка v: [42 35 29 23 17  8]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [ ]:
v = np.array([-12, -4, 3, 18, 27, 35, 48])

#1 Обмежте всі значення діапазоном від -5 до 30
clipped = np.clip(v, -5, 30)
print("Оригінал:  ", v)
print("Обмежений: ", clipped)

#1.2 Додатково визначте індекси елементів, які були змінені.
idecs_elem = np.where(v != clipped)[0]
print("Індекси змінених елементів:", idecs_elem)
print("Значення до зміни:", v[idecs_elem])
print("Значення після зміни:", clipped[idecs_elem])

Оригінал:   [-12  -4   3  18  27  35  48]
Обмежений:  [-5 -4  3 18 27 30 30]
Індекси змінених елементів: [0 5 6]
Значення до зміни: [-12  35  48]
Значення після зміни: [-5 30 30]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [ ]:
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

#1 та 2 Знайдіть усі унікальні значення та визначте кількість появ кожного значення.
values, counts = np.unique(v, return_counts=True)
print("Унікальні значення:", values)
print("Кількість появ:    ", counts)

#3 Знайдіть значення, яке трапляється найчастіше.
frequentcy = values[np.argmax(counts)]
print("Найчастіше значення:", frequentcy, "(з'являється", counts.max(), "разів)")

Унікальні значення: [2 4 7 9]
Кількість появ:     [3 3 4 1]
Найчастіше значення: 7 (з'являється 4 разів)


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [ ]:
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

#1 Поворот на 90° за годинниковою стрілкою
rot_90_za = np.rot90(A, k=-1)
print("90° за годинниковою стрілкою:", rot_90_za)

#2 Поворот на 180°
rot_180 = np.rot90(A, k=2)
print("180°:", rot_180)

#3 Поворот на 90° проти годинникової стрілки
rot_90_pr = np.rot90(A, k=1)
print("90° проти годинникової стрілки:", rot_90_pr)

90° за годинниковою стрілкою: [[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]
180°: [[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]
90° проти годинникової стрілки: [[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [ ]:
import numpy as np

A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
print("Форма оригіналу:", A.shape)

#1Рамка шириною 1, заповнена -1
pad_1 = np.pad(A, pad_width=1, mode='constant', constant_values=-1)
print("\nРамка шириною 1 (-1):\n", pad_1)
print("Форма:", pad_1.shape)

#2 Рамка шириною 2, заповнена нулями
pad_2 = np.pad(A, pad_width=2, mode='constant', constant_values=0)
print("Рамка шириною 2 (0):", pad_2)
print("Форма:", pad_2.shape)

Форма оригіналу: (3, 3)

Рамка шириною 1 (-1):
 [[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
Форма: (5, 5)
Рамка шириною 2 (0): [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Форма: (7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [ ]:
import numpy as np

A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

print("Оригінал:\n", A)

#1 Переставте рядки відповідно до row_order.
A_rows = A[row_order, :]
print("\nПісля перестановки рядків:\n", A_rows)

#2 Після цього переставте стовпці відповідно до col_order.
A_col = A_rows[:, col_order]
print("\nПісля перестановки стовпців:\n", A_col)

#3 Відновлення оригіналу за допомогою обернених перестановок
inv_col_order = np.argsort(col_order)
inv_row_order = np.argsort(row_order)

A_restored = A_col[:, inv_col_order]
A_restored = A_restored[inv_row_order, :]

print("Відновлена матриця:", A_restored)
print("Чи збігається з оригіналом:", np.array_equal(A_restored, A))

Оригінал:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]

Після перестановки рядків:
 [[31 32 33 34]
 [11 12 13 14]
 [41 42 43 44]
 [21 22 23 24]]

Після перестановки стовпців:
 [[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]
Відновлена матриця: [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
Чи збігається з оригіналом: True


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [ ]:
import numpy as np
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

#1 Отримайте верхню трикутну частину разом із головною діагоналлю.
upper = np.triu(A)
print("Верхня трикутна (з діагоналлю):", upper)

#2 Отримайте нижню трикутну частину разом із головною діагоналлю.
lower = np.tril(A)
print("Нижня трикутна (з діагоналлю):", lower)

#3 Отримайте строго верхню та строго нижню частини.
strict_upper = np.triu(A, k=1)
strict_lower = np.tril(A, k=-1)
print("Строго верхня (k=1):", strict_upper)
print("Строго нижня (k=-1):", strict_lower)

#4 Відновіть початкову матрицю з нижньої та строго верхньої частин.
restored = lower + strict_upper
print("Відновлена матриця (lower + strict_upper):", restored)
print("Чи збігається з оригіналом:", np.array_equal(restored, A))

Верхня трикутна (з діагоналлю): [[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]
Нижня трикутна (з діагоналлю): [[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]
Строго верхня (k=1): [[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]
Строго нижня (k=-1): [[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]
Відновлена матриця (lower + strict_upper): [[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]
Чи збігається з оригіналом: True


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [ ]:
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

#1 Побудуйте матрицю зовнішнього добутку.
M = np.outer(a, b)
print("Зовнішній добуток a і b:", M)

#2 Визначте її форму.
print("Форма:", M.shape)

#3 Перевірте, що елемент [2, 1] дорівнює a[2] * b[1].
element = M[2, 1]
manual = a[2] * b[1]
print("M[2, 1] =", element)
print("a[2] * b[1] =", manual)
print("Збігається:", element == manual)

Зовнішній добуток a і b: [[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]
Форма: (4, 3)
M[2, 1] = 35
a[2] * b[1] = 35
Збігається: True


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [ ]:
A = np.array([
    [2, 1],
    [0, 3]
])
B = np.array([
    [1, 4],
    [2, 0]
])

#1 Обчисліть добуток Кронекера A і B.
AB = np.kron(A, B)
print("kron(A, B) =", AB)
print("Форма:", AB.shape)

#2 Обчисліть добуток Кронекера B і A.
BA = np.kron(B, A)
print("kron(B, A) =", BA)
print("Форма:", BA.shape)

#3 Порівняйте результати та їх форми.
print("Форми однакові:", AB.shape == BA.shape)
print("Матриці збігаються:", np.array_equal(AB, BA))

kron(A, B) = [[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]
Форма: (4, 4)
kron(B, A) = [[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]
Форма: (4, 4)
Форми однакові: True
Матриці збігаються: False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [ ]:
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])

A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])

commutator1 = A1 @ B1 - B1 @ A1
print("Комутатор [A1, B1]:")
print(commutator1)
print("AB1 = BA1:", np.allclose(A1 @ B1, B1 @ A1))

print()

commutator2 = A2 @ B2 - B2 @ A2
print("Комутатор [A2, B2]:")
print(commutator2)
print("AB2 = BA2:", np.allclose(A2 @ B2, B2 @ A2))

Комутатор [A1, B1]:
[[0 0]
 [0 0]]
AB1 = BA1: True

Комутатор [A2, B2]:
[[ 0 -6]
 [-3  0]]
AB2 = BA2: False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [ ]:
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

quad_form_x = x @ A @ x
print("Квадратична форма x^T * A * x =", quad_form_x)

quad_forms_X = np.einsum('bi,ib,bj->b', X, A, X)
print("Квадратичні форми для рядків X:", quad_forms_X)

Квадратична форма x^T * A * x = 35
Квадратичні форми для рядків X: [36 15  0]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [ ]:
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
#1 Обчисліть A².
A2 = np.linalg.matrix_power(A, 2)
print("A^2 =")
print(A2)
#2 Обчисліть A³.
A3 = np.linalg.matrix_power(A, 3)
print()
print("A^3 =")
print(A3)
#3 Перевірте, що A³ = A² @ A.
check = A2 @ A
print()
print("A^2 @ A =")
print(check)
print()
print("A^3 = A^2 @ A:", np.array_equal(A3, check))

A^2 =
[[1 2 1]
 [1 1 2]
 [2 1 1]]

A^3 =
[[2 3 3]
 [3 2 3]
 [3 3 2]]

A^2 @ A =
[[2 3 3]
 [3 2 3]
 [3 3 2]]

A^3 = A^2 @ A: True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [ ]:
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

#1 Знайдіть ранг кожної матриці.
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print("Ранг A:", rank_A)
print("Ранг B:", rank_B)

#2 Визначте, яка з них має повний ранг.
n = A.shape[0]
print()
print("A має повний ранг:", rank_A == n)
print("B має повний ранг:", rank_B == n)

Ранг A: 3
Ранг B: 2

A має повний ранг: True
B має повний ранг: False


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [ ]:
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

#1 Знайдіть власні значення та власні вектори.
values, vectors = np.linalg.eigh(A)
print("Власні значення:", values)
print("Власні вектори (стовпці):")
print(vectors)

#2 Перевірте співвідношення A @ V = V * λ.
left_side = A @ vectors
right_side = vectors * values

#3 Виведіть результат перевірки через np.allclose().
print()
print("A @ V =")
print(left_side)
print()
print("V * lambda =")
print(right_side)
print()
print("Рівність виконується:", np.allclose(left_side, right_side))

Власні значення: [2. 7.]
Власні вектори (стовпці):
[[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]

A @ V =
[[ 0.89442719 -6.26099034]
 [-1.78885438 -3.13049517]]

V * lambda =
[[ 0.89442719 -6.26099034]
 [-1.78885438 -3.13049517]]

Рівність виконується: True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [ ]:
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

#1 Сформуйте матрицю ознак зі стовпця одиниць і значень x.
M = np.column_stack((np.ones_like(x), x))
print("Матриця ознак M:")
print(M)

#2 Знайдіть коефіцієнти a і b методом найменших квадратів.
coeffs, residuals, rank, sv = np.linalg.lstsq(M, y, rcond=None)
a, b = coeffs
print()
print("a =", a)
print("b =", b)

#3 Обчисліть прогнозні значення y.
y_pred = M @ coeffs
print()
print("Прогнозні значення y:", y_pred)
print("Реальні значення y:  ", y)

#4 Знайдіть суму квадратів залишків
sum_res = np.sum((y - y_pred) ** 2)
print()
print("Сума квадратів залишків:", sum_res)

Матриця ознак M:
[[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]

a = 2.019999999999998
b = 2.0100000000000002

Прогнозні значення y: [ 2.02  4.03  6.04  8.05 10.06]
Реальні значення y:   [ 2.2  3.8  6.1  7.9 10.2]

Сума квадратів залишків: 0.13099999999999973
