<a href="https://colab.research.google.com/github/KostantinDubnitskyi/Methodd/blob/main/%D0%9B%D1%80_4_(%D0%94%D1%83%D0%B1%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Встaновлення numpy
!pip install numpy

In [ ]:
#1.Знайти матрицю С = 𝐴𝐵 − 𝐵𝐴:
import numpy as np
A = np.array([[1, 2], [4, -1]])
B = np.array([[2, -3], [-4, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

C = AB - BA

print("Матриця С:")

print(C)


Матриця С:
[[ 4 -8]
 [12 -4]]


In [ ]:
#2.Піднести матриці до степеня:
import numpy as np
A = np.array([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])
A_1 = np.dot(A, A)

print("A^2 =")
print(A_1)

A^2 =
[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [ ]:
#3. Знайти добуток матриць:
import numpy as np
A = np.array([[3, 5], [6, -1]])

B = np.array([[2, 1], [-3, 2]])
C = np.dot(A, B)

print("C =")
print(C)

C =
[[-9 13]
 [15  4]]


In [ ]:
#4.Обчислити визначники:
import numpy as np
a = np.array([[1, 2, 3], [-1, 2, 1], [1, 3, 2]])

det_a = np.linalg.det(a)

print("Визначник матриці a:")
print(round(det_a, 2))

Визначник матриці a:
-8.0


In [ ]:
#5.Обчислити визначники:
import numpy as np

a = np.array([[1, 2, 3, 4], [-2, 1, -4, 3], [3, -4, -1, 2], [4, 3, -2, -1]])

det_a = np.linalg.det(a)

print("Визначник матриці:")
print(round(det_a, 2))

Визначник матриці:
900.0


In [ ]:
#6.Знайти обернену матрицю до матриць:
import numpy as np
a = np.array([[1, 1, 1, 1], [1, 1, -1, -1], [1, -1, 1, -1], [1, -1, -1, 1]])

a_inv = np.linalg.inv(a)

print("Обернена матриця а:")
print(a_inv)

Обернена матриця а:
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]


In [ ]:
#7.Визначити ранг матриці:
import numpy as np
a = np.array([[1, 2, 3, 4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])

rank_a = np.linalg.matrix_rank(a)

print("Ранг матриці a:", rank_a)

Ранг матриці a: 2


In [ ]:
#8.Розв’язати систему лінійних рівнянь методом Крамера матричним методом (тобто обчислити обернену матрицю) і м. Гауса. + перевірка solve()
import numpy as np

# Матричний метод
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))  # Округлюємо до десятих
    return solutions

# Метод Гауса
def gauss_method(a, b):
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x

def main():
    # Приклад матриці A и вектора B для розв'язку системи рівнянь Ax = B
    a = np.array([[2.0, -1.0, 1.0], [3.0, 2.0, 2.0], [1.0, -2.0, 1.0]])

    b = np.array([2.0, -2.0, 1.0])

    # Матричний метод
    x_matrix = matrix_method(a, b)
    print("Матричний метод:", x_matrix)

    # Метод Крамера
    x_cramer = cramer_method(a, b)
    print("Метод Крамера:", x_cramer)

    # Метод Гауса
    x_gauss = gauss_method(a, b)
    print("Метод Гауса:", x_gauss)

    # Перевірка за допомогою np.linalg.solve
    x_check = np.linalg.solve(a, b)
    print('Перевірка:')
    print('x =', x_check.round(1))

if __name__ == "__main__":
    main()

Матричний метод: [ 2. -1. -3.]
Метод Крамера: [2.0, -1.0, -3.0]
Метод Гауса: [ 2. -1. -3.]
Перевірка:
x = [ 133.  -68. -332.]


In [ ]:
import numpy as np

N = 3  # рядки
M = 3  # стовпці

#Задаємо матрицю з рандомними елементами в діапазоні від -25 до 25
A = np.random.randint(-25, 25, size=(N, M))

print("Матриця A:")
print(A)

#Кількість негативних елум. у кожному стовпці
n_columns = np.sum(A < 0, axis=0)

#Кількість негативних елем. у кожному рядку
n_rows = np.sum(A < 0, axis=1)

print("\nКількість негативних елем. у кожному стовпці:")
print(n_columns)

print("\nКількість негативних елем. у кожному рядку:")
print(n_rows)

Матриця A:
[[-13  12 -25]
 [  6 -10  16]
 [  8 -23  10]]

Кількість негативних елем. у кожному стовпці:
[1 2 1]

Кількість негативних елем. у кожному рядку:
[2 1 1]
